export interface Country {
  name: string;
  code: string;
  difficulty?: 'easy' | 'medium' | 'hard';
}

export type Difficulty = 'easy' | 'medium' | 'hard';

// Países fáciles - Banderas muy reconocibles
export const EASY_COUNTRIES: Country[] = [
  { name: 'Alemania', code: 'DE', difficulty: 'easy' },
  { name: 'Argentina', code: 'AR', difficulty: 'easy' },
  { name: 'Australia', code: 'AU', difficulty: 'easy' },
  { name: 'Austria', code: 'AT', difficulty: 'easy' },
  { name: 'Bélgica', code: 'BE', difficulty: 'easy' },
  { name: 'Brasil', code: 'BR', difficulty: 'easy' },
  { name: 'Bulgaria', code: 'BG', difficulty: 'easy' },
  { name: 'Canadá', code: 'CA', difficulty: 'easy' },
  { name: 'Chile', code: 'CL', difficulty: 'easy' },
  { name: 'China', code: 'CN', difficulty: 'easy' },
  { name: 'Colombia', code: 'CO', difficulty: 'easy' },
  { name: 'Corea del Sur', code: 'KR', difficulty: 'easy' },
  { name: 'Croacia', code: 'HR', difficulty: 'easy' },
  { name: 'Dinamarca', code: 'DK', difficulty: 'easy' },
  { name: 'Ecuador', code: 'EC', difficulty: 'easy' },
  { name: 'Emiratos Árabes Unidos', code: 'AE', difficulty: 'easy' },
  { name: 'España', code: 'ES', difficulty: 'easy' },
  { name: 'Estados Unidos', code: 'US', difficulty: 'easy' },
  { name: 'Finlandia', code: 'FI', difficulty: 'easy' },
  { name: 'Francia', code: 'FR', difficulty: 'easy' },
  { name: 'Grecia', code: 'GR', difficulty: 'easy' },
  { name: 'Groenlandia', code: 'GL', difficulty: 'easy' },
  { name: 'Holanda', code: 'NL', difficulty: 'easy' },
  { name: 'Honduras', code: 'HN', difficulty: 'easy' },
  { name: 'Hungría', code: 'HU', difficulty: 'easy' },
  { name: 'India', code: 'IN', difficulty: 'easy' },
  { name: 'Irlanda', code: 'IE', difficulty: 'easy' },
  { name: 'Islandia', code: 'IS', difficulty: 'easy' },
  { name: 'Israel', code: 'IL', difficulty: 'easy' },
  { name: 'Italia', code: 'IT', difficulty: 'easy' },
  { name: 'Japón', code: 'JP', difficulty: 'easy' },
  { name: 'Marruecos', code: 'MA', difficulty: 'easy' },
  { name: 'México', code: 'MX', difficulty: 'easy' },
  { name: 'Noruega', code: 'NO', difficulty: 'easy' },
  { name: 'Perú', code: 'PE', difficulty: 'easy' },
  { name: 'Polonia', code: 'PL', difficulty: 'easy' },
  { name: 'Portugal', code: 'PT', difficulty: 'easy' },
  { name: 'Puerto Rico', code: 'PR', difficulty: 'easy' },
  { name: 'Reino Unido', code: 'GB', difficulty: 'easy' },
  { name: 'República Checa', code: 'CZ', difficulty: 'easy' },
  { name: 'Rusia', code: 'RU', difficulty: 'easy' },
  { name: 'Rumania', code: 'RO', difficulty: 'easy' },
  { name: 'Arabia Saudí', code: 'SA', difficulty: 'easy' },
  { name: 'Sudáfrica', code: 'ZA', difficulty: 'easy' },
  { name: 'Sudán', code: 'SD', difficulty: 'easy' },
  { name: 'Suecia', code: 'SE', difficulty: 'easy' },
  { name: 'Suiza', code: 'CH', difficulty: 'easy' },
  { name: 'Tailandia', code: 'TH', difficulty: 'easy' },
  { name: 'Turquía', code: 'TR', difficulty: 'easy' },
  { name: 'Ucrania', code: 'UA', difficulty: 'easy' },
  { name: 'Uruguay', code: 'UY', difficulty: 'easy' },
  { name: 'Venezuela', code: 'VE', difficulty: 'easy' },
];

// Países de dificultad media - Banderas con características distinguibles
export const MEDIUM_COUNTRIES: Country[] = [
  { name: 'Afganistán', code: 'AF', difficulty: 'medium' },
  { name: 'Albania', code: 'AL', difficulty: 'medium' },
  { name: 'Andorra', code: 'AD', difficulty: 'medium' },
  { name: 'Angola', code: 'AO', difficulty: 'medium' },
  { name: 'Antártida', code: 'AQ', difficulty: 'medium' },
  { name: 'Armenia', code: 'AM', difficulty: 'medium' },
  { name: 'Bahamas', code: 'BS', difficulty: 'medium' },
  { name: 'Bangladés', code: 'BD', difficulty: 'medium' },
  { name: 'Barbados', code: 'BB', difficulty: 'medium' },
  { name: 'Baréin', code: 'BH', difficulty: 'medium' },
  { name: 'Belice', code: 'BZ', difficulty: 'medium' },
  { name: 'Benín', code: 'BJ', difficulty: 'medium' },
  { name: 'Bermudas', code: 'BM', difficulty: 'medium' },
  { name: 'Bielorrusia', code: 'BY', difficulty: 'medium' },
  { name: 'Birmania', code: 'MM', difficulty: 'medium' },
  { name: 'Botsuana', code: 'BW', difficulty: 'medium' },
  { name: 'Bosnia y Herzegovina', code: 'BA', difficulty: 'medium' },
  { name: 'Bután', code: 'BT', difficulty: 'medium' },
  { name: 'Cabo Verde', code: 'CV', difficulty: 'medium' },
  { name: 'Camboya', code: 'KH', difficulty: 'medium' },
  { name: 'Camerún', code: 'CM', difficulty: 'medium' },
  { name: 'Chad', code: 'TD', difficulty: 'medium' },
  { name: 'Chipre', code: 'CY', difficulty: 'medium' },
  { name: 'Corea del Norte', code: 'KP', difficulty: 'medium' },
  { name: 'Costa de Marfil', code: 'CI', difficulty: 'medium' },
  { name: 'Costa Rica', code: 'CR', difficulty: 'medium' },
  { name: 'Cuba', code: 'CU', difficulty: 'medium' },
  { name: 'Dominica', code: 'DM', difficulty: 'medium' },
  { name: 'Egipto', code: 'EG', difficulty: 'medium' },
  { name: 'El Salvador', code: 'SV', difficulty: 'medium' },
  { name: 'Eslovaquia', code: 'SK', difficulty: 'medium' },
  { name: 'Eslovenia', code: 'SI', difficulty: 'medium' },
  { name: 'Estados Unidos Menores', code: 'UM', difficulty: 'medium' },
  { name: 'Estonia', code: 'EE', difficulty: 'medium' },
  { name: 'Etiopía', code: 'ET', difficulty: 'medium' },
  { name: 'Fiji', code: 'FJ', difficulty: 'medium' },
  { name: 'Filipinas', code: 'PH', difficulty: 'medium' },
  { name: 'Gambia', code: 'GM', difficulty: 'medium' },
  { name: 'Georgia', code: 'GE', difficulty: 'medium' },
  { name: 'Gibraltar', code: 'GI', difficulty: 'medium' },
  { name: 'Ghana', code: 'GH', difficulty: 'medium' },
  { name: 'Guatemala', code: 'GT', difficulty: 'medium' },
  { name: 'Guernsey', code: 'GG', difficulty: 'medium' },
  { name: 'Guinea', code: 'GN', difficulty: 'medium' },
  { name: 'Guinea Ecuatorial', code: 'GQ', difficulty: 'medium' },
  { name: 'Guinea-Bisáu', code: 'GW', difficulty: 'medium' },
  { name: 'Haití', code: 'HT', difficulty: 'medium' },
  { name: 'Heard e Islas McDonald', code: 'HM', difficulty: 'medium' },
  { name: 'Hong Kong', code: 'HK', difficulty: 'medium' },
  { name: 'Iglesia Católica', code: 'VA', difficulty: 'medium' },
  { name: 'Indonesia', code: 'ID', difficulty: 'medium' },
  { name: 'Irak', code: 'IQ', difficulty: 'medium' },
  { name: 'Irán', code: 'IR', difficulty: 'medium' },
  { name: 'Isla Ascensión', code: 'SH', difficulty: 'medium' },
  { name: 'Isla de Navidad', code: 'CX', difficulty: 'medium' },
  { name: 'Islas Åland', code: 'AX', difficulty: 'medium' },
  { name: 'Islas Caimán', code: 'KY', difficulty: 'medium' },
  { name: 'Islas Coco', code: 'CC', difficulty: 'medium' },
  { name: 'Islas Cook', code: 'CK', difficulty: 'medium' },
  { name: 'Islas Faroe', code: 'FO', difficulty: 'medium' },
  { name: 'Islas Malvinas', code: 'FK', difficulty: 'medium' },
  { name: 'Islas Mariana del Norte', code: 'MP', difficulty: 'medium' },
  { name: 'Islas Marshall', code: 'MH', difficulty: 'medium' },
  { name: 'Isla de Man', code: 'IM', difficulty: 'medium' },
  { name: 'Jamaica', code: 'JM', difficulty: 'medium' },
  { name: 'Jersey', code: 'JE', difficulty: 'medium' },
  { name: 'Jordania', code: 'JO', difficulty: 'medium' },
  { name: 'Kenia', code: 'KE', difficulty: 'medium' },
  { name: 'Kiribati', code: 'KI', difficulty: 'medium' },
  { name: 'Kirguistán', code: 'KG', difficulty: 'medium' },
  { name: 'Kuwait', code: 'KW', difficulty: 'medium' },
  { name: 'Laos', code: 'LA', difficulty: 'medium' },
  { name: 'Lesoto', code: 'LS', difficulty: 'medium' },
  { name: 'Letonia', code: 'LV', difficulty: 'medium' },
  { name: 'Líbano', code: 'LB', difficulty: 'medium' },
  { name: 'Liberia', code: 'LR', difficulty: 'medium' },
  { name: 'Libia', code: 'LY', difficulty: 'medium' },
  { name: 'Liechtenstein', code: 'LI', difficulty: 'medium' },
  { name: 'Lituania', code: 'LT', difficulty: 'medium' },
  { name: 'Luxemburgo', code: 'LU', difficulty: 'medium' },
  { name: 'Macao', code: 'MO', difficulty: 'medium' },
  { name: 'Madagascar', code: 'MG', difficulty: 'medium' },
  { name: 'Malasia', code: 'MY', difficulty: 'medium' },
  { name: 'Malawi', code: 'MW', difficulty: 'medium' },
  { name: 'Maldivas', code: 'MV', difficulty: 'medium' },
  { name: 'Mali', code: 'ML', difficulty: 'medium' },
  { name: 'Malta', code: 'MT', difficulty: 'medium' },
  { name: 'Martinica', code: 'MQ', difficulty: 'medium' },
  { name: 'Mauritania', code: 'MR', difficulty: 'medium' },
  { name: 'Mauricio', code: 'MU', difficulty: 'medium' },
  { name: 'Mayotte', code: 'YT', difficulty: 'medium' },
  { name: 'Micronesia', code: 'FM', difficulty: 'medium' },
  { name: 'Moldavia', code: 'MD', difficulty: 'medium' },
  { name: 'Mónaco', code: 'MC', difficulty: 'medium' },
  { name: 'Mongolia', code: 'MN', difficulty: 'medium' },
  { name: 'Montserrat', code: 'MS', difficulty: 'medium' },
  { name: 'Mozambique', code: 'MZ', difficulty: 'medium' },
  { name: 'Namibia', code: 'NA', difficulty: 'medium' },
  { name: 'Nauru', code: 'NR', difficulty: 'medium' },
  { name: 'Nepal', code: 'NP', difficulty: 'medium' },
  { name: 'Nueva Zelanda', code: 'NZ', difficulty: 'medium' },
  { name: 'Nicaragua', code: 'NI', difficulty: 'medium' },
  { name: 'Níger', code: 'NE', difficulty: 'medium' },
  { name: 'Nigeria', code: 'NG', difficulty: 'medium' },
  { name: 'Niue', code: 'NU', difficulty: 'medium' },
  { name: 'Omán', code: 'OM', difficulty: 'medium' },
  { name: 'Pakistán', code: 'PK', difficulty: 'medium' },
  { name: 'Palaos', code: 'PW', difficulty: 'medium' },
  { name: 'Panamá', code: 'PA', difficulty: 'medium' },
  { name: 'Papúa Nueva Guinea', code: 'PG', difficulty: 'medium' },
  { name: 'Paraguay', code: 'PY', difficulty: 'medium' },
  { name: 'Polinesia Francesa', code: 'PF', difficulty: 'medium' },
  { name: 'Qatar', code: 'QA', difficulty: 'medium' },
  { name: 'República Centro Africana', code: 'CF', difficulty: 'medium' },
  { name: 'República del Congo', code: 'CD', difficulty: 'medium' },
  { name: 'República Dominicana', code: 'DO', difficulty: 'medium' },
  { name: 'Reunión', code: 'RE', difficulty: 'medium' },
  { name: 'Ruanda', code: 'RW', difficulty: 'medium' },
  { name: 'Sahara Occidental', code: 'EH', difficulty: 'medium' },
  { name: 'Saint Kitts y Nevis', code: 'KN', difficulty: 'medium' },
  { name: 'Samoa', code: 'WS', difficulty: 'medium' },
  { name: 'Samoa Americana', code: 'AS', difficulty: 'medium' },
  { name: 'San Bartolomé', code: 'BL', difficulty: 'medium' },
  { name: 'San Marino', code: 'SM', difficulty: 'medium' },
  { name: 'San Martín', code: 'MF', difficulty: 'medium' },
  { name: 'San Pedro y Miquelón', code: 'PM', difficulty: 'medium' },
  { name: 'San Vicente y las Granadinas', code: 'VC', difficulty: 'medium' },
  { name: 'Santa Elena', code: 'SH', difficulty: 'medium' },
  { name: 'Santa Lucía', code: 'LC', difficulty: 'medium' },
  { name: 'Santo Tomé y Príncipe', code: 'ST', difficulty: 'medium' },
  { name: 'Senegal', code: 'SN', difficulty: 'medium' },
  { name: 'Serbia', code: 'RS', difficulty: 'medium' },
  { name: 'Seychelles', code: 'SC', difficulty: 'medium' },
  { name: 'Sierra Leona', code: 'SL', difficulty: 'medium' },
  { name: 'Singapur', code: 'SG', difficulty: 'medium' },
  { name: 'Sint Maarten', code: 'SX', difficulty: 'medium' },
  { name: 'Siria', code: 'SY', difficulty: 'medium' },
  { name: 'Somalia', code: 'SO', difficulty: 'medium' },
  { name: 'Sri Lanka', code: 'LK', difficulty: 'medium' },
  { name: 'Suazilandia', code: 'SZ', difficulty: 'medium' },
  { name: 'Sudán del Sur', code: 'SS', difficulty: 'medium' },
  { name: 'Surinam', code: 'SR', difficulty: 'medium' },
  { name: 'Svalbard y Jan Mayen', code: 'SJ', difficulty: 'medium' },
  { name: 'Taiwán', code: 'TW', difficulty: 'medium' },
  { name: 'Tayikistán', code: 'TJ', difficulty: 'medium' },
  { name: 'Territorios Franceses del Sur', code: 'TF', difficulty: 'medium' },
  { name: 'Territorios Británicos del Océano Índico', code: 'IO', difficulty: 'medium' },
  { name: 'Timor Oriental', code: 'TL', difficulty: 'medium' },
  { name: 'Togo', code: 'TG', difficulty: 'medium' },
  { name: 'Tokelau', code: 'TK', difficulty: 'medium' },
  { name: 'Tonga', code: 'TO', difficulty: 'medium' },
  { name: 'Trinidad y Tobago', code: 'TT', difficulty: 'medium' },
  { name: 'Túnez', code: 'TN', difficulty: 'medium' },
  { name: 'Turkmenistán', code: 'TM', difficulty: 'medium' },
  { name: 'Tuvalu', code: 'TV', difficulty: 'medium' },
  { name: 'Uganda', code: 'UG', difficulty: 'medium' },
  { name: 'Unión Europea', code: 'EU', difficulty: 'medium' },
  { name: 'Uzbekistán', code: 'UZ', difficulty: 'medium' },
  { name: 'Vaticano', code: 'VA', difficulty: 'medium' },
  { name: 'Vietnám', code: 'VN', difficulty: 'medium' },
  { name: 'Yemen', code: 'YE', difficulty: 'medium' },
];

// Países difíciles - Banderas complicadas y poco conocidas
export const HARD_COUNTRIES: Country[] = [
  { name: 'Abkhazia', code: 'AK', difficulty: 'hard' },
  { name: 'Anguila', code: 'AI', difficulty: 'hard' },
  { name: 'Antillas Neerlandesas', code: 'AN', difficulty: 'hard' },
  { name: 'Artsakh', code: 'AH', difficulty: 'hard' },
  { name: 'Aruba', code: 'AW', difficulty: 'hard' },
  { name: 'Azerbaiyán', code: 'AZ', difficulty: 'hard' },
  { name: 'Bonaire, Sint Eustatius y Saba', code: 'BQ', difficulty: 'hard' },
  { name: 'Isla Bouvet', code: 'BV', difficulty: 'hard' },
  { name: 'Brunéi', code: 'BN', difficulty: 'hard' },
  { name: 'Burkina Faso', code: 'BF', difficulty: 'hard' },
  { name: 'Burundi', code: 'BI', difficulty: 'hard' },
  { name: 'Bután', code: 'BT', difficulty: 'hard' },
  { name: 'Chipre Septentrional', code: 'NY', difficulty: 'hard' },
  { name: 'Comoras', code: 'KM', difficulty: 'hard' },
  { name: 'Congo', code: 'CG', difficulty: 'hard' },
  { name: 'Curazao', code: 'CW', difficulty: 'hard' },
  { name: 'Eritrea', code: 'ER', difficulty: 'hard' },
  { name: 'Fiji', code: 'FJ', difficulty: 'hard' },
  { name: 'Gambia', code: 'GM', difficulty: 'hard' },
  { name: 'Guam', code: 'GU', difficulty: 'hard' },
  { name: 'Guayana Francesa', code: 'GF', difficulty: 'hard' },
  { name: 'Guayana', code: 'GY', difficulty: 'hard' },
  { name: 'Iglesia Católica', code: 'VA', difficulty: 'hard' },
  { name: 'Islas Georgias y Sándwich del Sur', code: 'GS', difficulty: 'hard' },
  { name: 'Islas Pitcairn', code: 'PN', difficulty: 'hard' },
  { name: 'Islas Salomón', code: 'SB', difficulty: 'hard' },
  { name: 'Islas Turcas y Caicos', code: 'TC', difficulty: 'hard' },
  { name: 'Islas Åland', code: 'AX', difficulty: 'hard' },
  { name: 'Islas Caimán', code: 'KY', difficulty: 'hard' },
  { name: 'Islas Coco', code: 'CC', difficulty: 'hard' },
  { name: 'Isla de Man', code: 'IM', difficulty: 'hard' },
  { name: 'Jersey', code: 'JE', difficulty: 'hard' },
  { name: 'Jordania', code: 'JO', difficulty: 'hard' },
  { name: 'Kenia', code: 'KE', difficulty: 'hard' },
  { name: 'Kiribati', code: 'KI', difficulty: 'hard' },
  { name: 'Kirguistán', code: 'KG', difficulty: 'hard' },
  { name: 'Kosovo', code: 'XK', difficulty: 'hard' },
  { name: 'Kuwait', code: 'KW', difficulty: 'hard' },
  { name: 'Líbano', code: 'LB', difficulty: 'hard' },
  { name: 'Macao', code: 'MO', difficulty: 'hard' },
  { name: 'Malawi', code: 'MW', difficulty: 'hard' },
  { name: 'Martinica', code: 'MQ', difficulty: 'hard' },
  { name: 'Mauritania', code: 'MR', difficulty: 'hard' },
  { name: 'Mauricio', code: 'MU', difficulty: 'hard' },
  { name: 'Mayotte', code: 'YT', difficulty: 'hard' },
  { name: 'Micronesia', code: 'FM', difficulty: 'hard' },
  { name: 'Mongolia', code: 'MN', difficulty: 'hard' },
  { name: 'Montserrat', code: 'MS', difficulty: 'hard' },
  { name: 'Nauru', code: 'NR', difficulty: 'hard' },
  { name: 'Niue', code: 'NU', difficulty: 'hard' },
  { name: 'Palaos', code: 'PW', difficulty: 'hard' },
  { name: 'Polinesia Francesa', code: 'PF', difficulty: 'hard' },
  { name: 'Reunión', code: 'RE', difficulty: 'hard' },
  { name: 'Ruanda', code: 'RW', difficulty: 'hard' },
  { name: 'Saint Kitts y Nevis', code: 'KN', difficulty: 'hard' },
  { name: 'San Martín', code: 'MF', difficulty: 'hard' },
  { name: 'San Pedro y Miquelón', code: 'PM', difficulty: 'hard' },
  { name: 'San Vicente y las Granadinas', code: 'VC', difficulty: 'hard' },
  { name: 'Santa Elena', code: 'SH', difficulty: 'hard' },
  { name: 'Santa Lucía', code: 'LC', difficulty: 'hard' },
  { name: 'Santo Tomé y Príncipe', code: 'ST', difficulty: 'hard' },
  { name: 'Siria', code: 'SY', difficulty: 'hard' },
  { name: 'Sri Lanka', code: 'LK', difficulty: 'hard' },
  { name: 'Suazilandia', code: 'SZ', difficulty: 'hard' },
  { name: 'Surinam', code: 'SR', difficulty: 'hard' },
  { name: 'Svalbard y Jan Mayen', code: 'SJ', difficulty: 'hard' },
  { name: 'Taiwán', code: 'TW', difficulty: 'hard' },
  { name: 'Tanzania', code: 'TZ', difficulty: 'hard' },
  { name: 'Tayikistán', code: 'TJ', difficulty: 'hard' },
  { name: 'Territorios Franceses del Sur', code: 'TF', difficulty: 'hard' },
  { name: 'Territorios Británicos del Océano Índico', code: 'IO', difficulty: 'hard' },
  { name: 'Timor Oriental', code: 'TL', difficulty: 'hard' },
  { name: 'Togo', code: 'TG', difficulty: 'hard' },
  { name: 'Tokelau', code: 'TK', difficulty: 'hard' },
  { name: 'Tonga', code: 'TO', difficulty: 'hard' },
  { name: 'Trinidad y Tobago', code: 'TT', difficulty: 'hard' },
  { name: 'Uganda', code: 'UG', difficulty: 'hard' },
  { name: 'Uzbekistán', code: 'UZ', difficulty: 'hard' },
  { name: 'Vanuatu', code: 'VU', difficulty: 'hard' },
  { name: 'Islas Vírgenes Británicas', code: 'VG', difficulty: 'hard' },
  { name: 'Islas Vírgenes de EE.UU.', code: 'VI', difficulty: 'hard' },
  { name: 'Yemen', code: 'YE', difficulty: 'hard' },
  { name: 'Zimbabue', code: 'ZW', difficulty: 'hard' },
  { name: 'Macedonia', code: 'MK', difficulty: 'hard' },
];

// Array con todos los países
export const ALL_COUNTRIES: Country[] = [
  ...EASY_COUNTRIES,
  ...MEDIUM_COUNTRIES,
  ...HARD_COUNTRIES,
];

// Función para obtener países por dificultad
export function getCountriesByDifficulty(difficulty: Difficulty): Country[] {
  switch (difficulty) {
    case 'easy':
      return EASY_COUNTRIES;
    case 'medium':
      return MEDIUM_COUNTRIES;
    case 'hard':
      return HARD_COUNTRIES;
    default:
      return ALL_COUNTRIES;
  }
}